version: '3'

services:

  wp_spaghetti_production:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - ${IP}:3091:80 # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app-spaghetti-production:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db_spaghetti_production
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    # depends_on:
    #   - db_spaghetti_production
    # links:
    #   - db_spaghetti_production
    networks:
      - wpsite_spaghetti_production

  pma_spaghetti_production:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db_spaghetti_production
      #PMA_USER: root
      #PMA_PASSWORD: "password"
      # PMA_PORT: 3307
      # MYSQL_DATABASE: "${DB_NAME}"
      # MYSQL_ROOT_HOST: db_spaghetti_production
      # MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - ${IP}:3078:80
    # links:
    #   - db_spaghetti_production:db
    networks:
      - wpsite_spaghetti_production
    # volumes:
    #   - db_data_spaghetti_production:/phpma

  db_spaghetti_production:
    image: mariadb:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3307:3307 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data-spaghetti-production:/docker-entrypoint-initdb.d
      - db_data_spaghetti_production:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    networks:
      - wpsite_spaghetti_production

volumes:
  db_data_spaghetti_production:

networks:
  wpsite_spaghetti_production:
