version: '3'

services:

# spaghetti website staging services

  wp_spaghetti_staging:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - ${IP}:3090:80 # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app-spaghetti-staging:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db_spaghetti_staging
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db_spaghetti_staging
    links:
      - db_spaghetti_staging
    networks:
      - wpsite_spaghetti_staging

  pma_spaghetti_staging:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      #PMA_ARBITRARY: 1
      PMA_HOST: db_spaghetti_staging
      # PMA_PORT: 3306
      # MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - ${IP}:3079:80
    links:
      - db_spaghetti_staging:db
    networks:
      - wpsite_spaghetti_staging
    # volumes:
    #   - db_data_spaghetti_staging:/phpma

  db_spaghetti_staging:
    image: mariadb:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data-spaghetti-staging:/docker-entrypoint-initdb.d
      - db_data_spaghetti_staging:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    networks:
      - wpsite_spaghetti_staging

volumes:
  db_data_spaghetti_staging:

networks:
  wpsite_spaghetti_staging:
